{% set name = "chemicals" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemicals-{{ version }}.tar.gz
  sha256: cc37239deca75dd5842d4413e851a03ef6beafc90c6cca62f05254690b4027ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - fluids >=0.1.86
    - pandas
    - python
    - scipy

test:
  imports:
    - chemicals
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CalebBell/chemicals
  summary: Chemical database of Chemical Engineering Design Library (ChEDL)
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - volpatto
    - CalebBell
    - yoelcortes
